import math
# print(math.ceil(0.1))
# print(math.ceil(2.4))
# print(math.ceil(5.3))
# print(math.ceil(6.9))
# print(math.ceil(-5.6))
# print(math.ceil(6.0))
# print(math.factorial(0))
# print(math.factorial(2))
# print(math.factorial(3))
# print(math.factorial(4))
# print(math.factorial(5))
# print(math.factorial(6))
# print(math.floor(23.5))
# print(math.floor(24.8))
# print(math.floor(-23.8))
# print(math.floor(-19.0))
# print(math.floor(-19.1))
# a=math.pow(3,2)
# print(a,type(a))
# b=3**2
# print(b,type(b))
# print(math.
# a=7
# b=15
# c=26
# d=32
# print(math.isqrt(a))
# print(math.isqrt(b))
# print(math.isqrt(c))
# print(math.isqrt(d))
# n=[1,2,3,4,5]
# print(sum(n))
# print(math.fsum(n))
# print(math.prod(n))
# print(math.trunc(-8.99))
# print(math.trunc(9.9))
# print(math.gcd(14,77))
# print(math.gcd(18,23))
# print(math.lcm(12,16))