# a="saikrish"
# print(a[-5:-7])
# b="pyhton"
# print(b[2:5])
# print(b[3:4])
# print(b[-1:-6])
# print(b[2:-5])
# print(b[-6:])

c="saikrish"
# print(c[ : :])
# print(c[0: : 1])
# print(c[ : : 3])
# print(c[ : : 4])
# print(c[ : : 5])
# print(c[ : : 6])
print(c[ : : 7])
print(c[ : : 8])
print(c[ : : 9])
print(c[ : : -1])
print(c[ : : -2])
print(c[ : : -3])
print(c[ : : -4])
print(c[ : : -5])
print(c[ : : -6])
print(c[ : : -7])
print(c[ : : -8])
print(c[ : : -9])
print(c[1: 6: ])
print(c[2: 5: ])
print(c[3: 4: ])
print(c[4: 3: ])
print(c[5: 2: ])
print(c[6: 3: ])
